import type { Listing } from './types'

export const listings: Listing[] = [
  {
    id: 'listing-paper-cups',
    organizationId: 'org-packplus',
    categoryId: 'cat-packaging',
    title: 'Branded Paper Coffee Cups',
    slug: 'branded-paper-coffee-cups',
    type: 'PRODUCT',
    description:
      'Single-wall and double-wall paper cups with custom logo printing for cafes and takeaway businesses.',
    city: 'Tirana',
    deliveryAreas: ['Tirana', 'Durres', 'Elbasan'],
    tags: ['coffee cups', 'custom branding', 'takeaway'],
    isFeatured: true,
    createdAt: '2026-06-05T12:00:00.000Z',
  },
  {
    id: 'listing-food-boxes',
    organizationId: 'org-packplus',
    categoryId: 'cat-packaging',
    title: 'Takeaway Food Boxes',
    slug: 'takeaway-food-boxes',
    type: 'PRODUCT',
    description:
      'Kraft food boxes for restaurants, fast food shops, bakeries, and delivery kitchens.',
    city: 'Tirana',
    deliveryAreas: ['Tirana', 'Durres', 'Fier', 'Vlore'],
    tags: ['food boxes', 'kraft packaging', 'delivery'],
    isFeatured: true,
    createdAt: '2026-06-07T14:10:00.000Z',
  },
  {
    id: 'listing-cafe-tables',
    organizationId: 'org-horeca-hub',
    categoryId: 'cat-furniture',
    title: 'Cafe Tables and Chairs',
    slug: 'cafe-tables-and-chairs',
    type: 'PRODUCT',
    description:
      'Indoor and outdoor tables and chairs for cafes, bars, restaurants, and hotel terraces.',
    city: 'Durres',
    deliveryAreas: ['Durres', 'Tirana', 'Kavaje'],
    tags: ['chairs', 'tables', 'horeca furniture'],
    isFeatured: false,
    createdAt: '2026-06-08T10:45:00.000Z',
  },
  {
    id: 'listing-coffee-machines',
    organizationId: 'org-horeca-hub',
    categoryId: 'cat-equipment',
    title: 'Commercial Coffee Machines',
    slug: 'commercial-coffee-machines',
    type: 'PRODUCT',
    description:
      'Espresso machines, grinders, water filters, and maintenance packages for cafes.',
    city: 'Durres',
    deliveryAreas: ['Albania'],
    tags: ['coffee machine', 'espresso', 'maintenance'],
    isFeatured: true,
    createdAt: '2026-06-09T15:25:00.000Z',
  },
  {
    id: 'listing-cleaning-package',
    organizationId: 'org-cleanpro',
    categoryId: 'cat-cleaning',
    title: 'Monthly Cleaning Supply Package',
    slug: 'monthly-cleaning-supply-package',
    type: 'SERVICE',
    description:
      'Recurring supply package for restaurants, offices, and retail spaces, including detergents and hygiene products.',
    city: 'Tirana',
    deliveryAreas: ['Tirana'],
    tags: ['cleaning supplies', 'hygiene', 'monthly supply'],
    isFeatured: false,
    createdAt: '2026-06-13T09:30:00.000Z',
  },
  {
    id: 'listing-wholesale-coffee',
    organizationId: 'org-coffee-line',
    categoryId: 'cat-food-beverage',
    title: 'Wholesale Coffee Beans',
    slug: 'wholesale-coffee-beans',
    type: 'PRODUCT',
    description:
      'Arabica and blended coffee beans for cafes, restaurants, hotels, and office coffee programs.',
    city: 'Shkoder',
    deliveryAreas: ['Shkoder', 'Lezhe', 'Tirana', 'Albania'],
    tags: ['coffee beans', 'wholesale', 'cafe supply'],
    isFeatured: true,
    createdAt: '2026-06-16T11:40:00.000Z',
  },
]
