import type { Organization } from './types'

export const organizations: Organization[] = [
  {
    id: 'org-packplus',
    name: 'PackPlus Albania',
    slug: 'packplus-albania',
    description:
      'Packaging supplier for cafes, bakeries, restaurants, and takeaway businesses.',
    city: 'Tirana',
    address: 'Rruga Industriale, Tirana',
    phone: '+355 69 111 2222',
    email: 'sales@packplus.al',
    website: 'https://packplus.al',
    categories: ['cat-packaging'],
    verificationStatus: 'VERIFIED',
    ownerId: 'user-owner-001',
    memberIds: ['user-member-001'],
    foundedYear: 2018,
    createdAt: '2026-06-04T10:35:00.000Z',
  },
  {
    id: 'org-horeca-hub',
    name: 'HoReCa Hub',
    slug: 'horeca-hub',
    description:
      'Equipment and furniture supplier for hotels, restaurants, bars, and cafes.',
    city: 'Durres',
    address: 'Lagjja 13, Durres',
    phone: '+355 68 222 3333',
    email: 'info@horecahub.al',
    website: 'https://horecahub.al',
    categories: ['cat-equipment', 'cat-furniture'],
    verificationStatus: 'PENDING',
    ownerId: 'user-owner-002',
    memberIds: [],
    foundedYear: 2020,
    createdAt: '2026-06-06T13:30:00.000Z',
  },
  {
    id: 'org-cleanpro',
    name: 'CleanPro Supplies',
    slug: 'cleanpro-supplies',
    description:
      'Cleaning materials, hygiene products, and recurring supply packages for offices and food businesses.',
    city: 'Tirana',
    address: 'Rruga 5 Maji, Tirana',
    phone: '+355 67 444 5555',
    email: 'contact@cleanpro.al',
    categories: ['cat-cleaning', 'cat-services'],
    verificationStatus: 'UNVERIFIED',
    ownerId: 'user-owner-001',
    memberIds: [],
    foundedYear: 2016,
    createdAt: '2026-06-12T11:00:00.000Z',
  },
  {
    id: 'org-coffee-line',
    name: 'Coffee Line Distribution',
    slug: 'coffee-line-distribution',
    description:
      'Wholesale coffee, syrups, paper goods, and barista equipment for cafes across Albania.',
    city: 'Shkoder',
    address: 'Rruga Kol Idromeno, Shkoder',
    phone: '+355 69 777 8888',
    email: 'hello@coffeeline.al',
    categories: ['cat-food-beverage', 'cat-equipment'],
    verificationStatus: 'VERIFIED',
    ownerId: 'user-owner-002',
    memberIds: [],
    foundedYear: 2019,
    createdAt: '2026-06-15T09:20:00.000Z',
  },
]
